version: "3"

services:
  db:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    restart: always
  dj:
    container_name: dj
    build: django
    restart: always
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "8081:80"
    depends_on:
      - db

  # ng:
  #   container_name: ng
  #   build: angular
  #   restart: always
  #   ports:
  #     - "8080:80"