# Generated by Django 3.2 on 2022-01-19 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['id'],
            },
        ),
    ]
