# Generated by Django 3.2 on 2022-01-21 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0002_activity_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='leaders',
            field=models.ManyToManyField(related_name='leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
