# Generated by Django 3.2 on 2022-01-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20220121_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='due_date',
            new_name='register_date_start',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_requirements',
            field=models.CharField(blank=True, choices=[('N', 'NoRequirements'), ('Mem', 'Member'), ('E', 'Experience'), ('B', 'Basic'), ('S', 'Suburb'), ('M', 'Middle'), ('A', 'Alpine'), ('So', 'Source'), ('T', 'Top')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_requirements_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('S', 'Suburb'), ('M', 'Middle'), ('A', 'Alpine')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='register_date_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip_date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
