# Generated by Django 3.2 on 2022-01-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20220126_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_requirements',
            field=models.CharField(blank=True, choices=[('N', '不限基本資格'), ('Mem', '會員(巳繳納本年度會費者)'), ('E', '溯溪體驗營結訓者'), ('B', '會員且初級溯溪營結訓'), ('Adv', '會員且進階營結訓'), ('S', '近郊溪行程(Suburb)'), ('M', '次高中游溪行程(Middle)'), ('A', '高山溪行程(Alpine)'), ('So', '溯源(Source)'), ('T', '溯源且登頂(Top)')], max_length=5, null=True),
        ),
    ]
